---
title: "Basic R"
author: "Techo"
date: "2025-03-03"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Basic Calculation ###
```{r}
# basic calculation 
1 + 1 
2 - 3 
2 * 5 
2 / 2 
# basic function in calculation
log(100)
sqrt(9)
exp(5) 
```
### Create Variable ###
```{r}
# use assign operator (<-) or =
x <- 100 
y <- 200 
one <- 1
Two <- 2
three <- 3
x + y
one * Two
one * Two + three
```
### Data structure ###
```{r}
# vector: a sequence of elements which share the same data type 
scores <- c(80, 99, 90, 72, 55) 
names <- c("David","Jan","Zuu","Tedy")
scores
names
```
```{r}
# try this 
scores + 10 
scores * 2 
updated <- c(5, 2, 3, 5, 7) 
new_scores <- scores + updated 
```
```{r}
new_scores[1] # 85 
new_scores[1:3] # 85 101 93 
new_scores[3:5] # 93 77 62 
```
### Data type ###
```{r}
# numeric vector 
x <- c(100, 200, 300) 
class(x) 
is.numeric(x)
x
# character vector
y <- c("Jason", "Momoa", "AquaMan") 
class(y) 
is.character(y)
y
# logical vector 
z <- c(TRUE, FALSE) 
class(z) 
is.logical(z) 
z
```
```{r}
# create character vector 
animals <- c("Dog", "Cat", "Dog", "Dog", "Hippo") 
class(animals)
animals
# convert character to factor 
animals <- as.factor(animals) 
class(animals)
animals
```
### Data frame ###
```{r}
# create three vectors 
students <- c("Joe", "Jason", "Momoa", "Anna", "Mary") 
scores <- c(69, 89, 92, 56, 87) 
grades <- c("C+", "B+", "A", "C", "B+") 
# create a single dataframe 
df <- data.frame(students, scores, grades) 
class(df)
df
```
### Simple function for Dataframe
```{r}
# try this in RStudio
str(df) 
head(df) 
tail(df) 
summary(df)
```
### Example Dataframe iris ###
```{r}
head(iris)
tail(iris)
str(iris)
```
```{r}
summary(iris)
```

### Edit or View column or row names ###
```{r}
colnames(iris)
rownames(iris)
```
### Subset dataframe ###
```{r}
# subset rows 1-10, all columns 
iris[1:5, ]
# subset rows 1-10, columns 1-5 
iris[1:5, 1:5] 
# subset all rows, columns 1-5 
head(iris[ , 1:5]) 
# subset by column names 
head(iris[ , "Sepal.Width"]) 
head(iris[ , c("Sepal.Length", "Petal.Length", "Species")])
```
### Create New subset dataframe ###
```{r}
subset_iris  <- iris[1:10, c("Sepal.Length", "Petal.Length", "Species")]
print(subset_iris )
```
### Data Wrangling ###
```{r}
### install extra package ###
## Call package ##
library(dplyr)
```
## Select() ##
```{r}
# select columns 1-5 
head(select(iris, 1:5)) 
# select columns Sepal.Length, Petal.Length, Species
head(select(iris, Sepal.Length, Petal.Length, Species))
```
## filter() ##
```{r}
# filter cars with Sepal.Length < 5
filter(iris, Sepal.Length < 5)
# filter cars with Petal.Length == 1.4 
filter(iris, Petal.Length == 1.4) 
```
### Equality Condition ###
# ==
# !=
# >
# >=
# <
# <=
```{r}
# see if any numbers <= 300 
numbers <- c(100, 200, 300, 50) 
numbers <= 100
# this will return FALSE because R is case-sensitive 
"hello" == "Hello" 
```
### Arrange data ###
```{r}
# sort column hp from low to high 
head(arrange(iris, Sepal.Length)) 
# sort column hp from high to low \
head(arrange(iris, desc(Sepal.Length))) 
```
### Basic Plot ###
```{r}
hist(iris$Sepal.Length)
boxplot(iris[,c("Sepal.Length", "Petal.Length")])
```
```{r}
data_for_bar_plot<-c(A=27,B=0,C=50,D=20)
barplot(data_for_bar_plot)
```

